config/routes.rb
Rails.application.routes.draw do
  get 'recipes/search'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # get '/recipes/search', to: 'recipes#search', as: 'search_recipes'
  get '/recipes', to: 'recipes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def search
    @recipes = SpoonacularService.search_recipes(params[:query])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpoonacularApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<h1>Recipes</h1>

<ul>
  <% @recipes.each do |recipe| %>
    <li><%= recipe['title'] %></li>
  <% end %>
</ul>

app/views/recipes/search.html.erb
<!-- app/views/recipes/search.html.erb -->

<h1>Search Recipes</h1>

<%= form_tag(recipes_search_path, method: :get) do %>
  <%= text_field_tag(:query, params[:query], placeholder: "Enter a search query") %>
  <%= submit_tag("Search") %>
<% end %>

<% if @recipes.present? %>
  <h2>Search Results</h2>
  <ul>
    <% @recipes.each do |recipe| %>
      <li><%= recipe['title'] %></li>
    <% end %>
  </ul>
<% else %>
  <p>No recipes found.</p>
<% end %>